### ISSUE TITLE
Request for basic assistance (not an issue)

### ISSUE THREAD

**Issue by ksadil** [CypherpunkArmory/UserLAnd-Assets-Support#69]
Hi 

UserLAnd works out of the box for me. Using the Debian asset, works perfect on the phone, but vnc connection refused from any other device. Can you please advise how to enable external connect via vnc.

Thanks
Kim

**Comment by corbinlc** [comment]
Please submit this issue here: https://github.com/CypherpunkArmory/UserLAnd/issues
